import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import '@progress/kendo-theme-default/dist/all.css';
import "./globals.css";
// contexts
import { CartProvider } from "../context/CartContext";
import { SessionProvider } from "next-auth/react";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <SessionProvider> */}
          <CartProvider>
            {children}
          </CartProvider>
        {/* </SessionProvider> */}

      </body>
    </html>
  );
}
